export interface CurrencyInfo {
  code: string;       // Сокращение валюты, например 'RUB'
  name: string;       // Название страны, например 'Россия'
  flagName: string;   // Имя файла флага (без расширения), например 'Russia'
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: 'AFN', name: 'Афганистан (афгани)', flagName: 'Afghanistan' },
  { code: 'EUR', name: 'Аландские острова (евро)', flagName: 'Aland' },
  { code: 'ALL', name: 'Албания (албанский лек)', flagName: 'Albania' },
  { code: 'DZD', name: 'Алжир (алжирский динар)', flagName: 'Algeria' },
  { code: 'USD', name: 'Американское Самоа (доллар США)', flagName: 'American-Samoa' },
  { code: 'AOA', name: 'Ангола (ангольская кванза)', flagName: 'Angola' },
  { code: 'XCD', name: 'Ангилья (восточно-карибский доллар)', flagName: 'Anguilla' },
  { code: 'ARS', name: 'Аргентина (аргентинский песо)', flagName: 'Argentina' },
  { code: 'AMD', name: 'Армения (армянский драм)', flagName: 'Armenia' },
  { code: 'AWG', name: 'Аруба (арубанский флорин)', flagName: 'Aruba' },
  { code: 'AUD', name: 'Австралия (австралийский доллар)', flagName: 'Australia' },
  { code: 'AZN', name: 'Азербайджан (азербайджанский манат)', flagName: 'Azerbaijan' },
  { code: 'BSD', name: 'Багамы (багамский доллар)', flagName: 'Bahamas' },
  { code: 'BHD', name: 'Бахрейн (бахрейнский динар)', flagName: 'Bahrain' },
  { code: 'BDT', name: 'Бангладеш (бангладешская така)', flagName: 'Bangladesh' },
  { code: 'BBD', name: 'Барбадос (барбадосский доллар)', flagName: 'Barbados' },
  { code: 'BYN', name: 'Беларусь (белорусский рубль)', flagName: 'Belarus' },
  { code: 'BZD', name: 'Белиз (белизский доллар)', flagName: 'Belize' },
  { code: 'XOF', name: 'Бенин (франк КФА ВСЕАО)', flagName: 'Benin' },
  { code: 'BMD', name: 'Бермуды (бермудский доллар)', flagName: 'Bermuda' },
  { code: 'INR', name: 'Бутан (индийская рупия)', flagName: 'Bhutan' },
  { code: 'BOB', name: 'Боливия (боливийский боливиано)', flagName: 'Bolivia' },
  { code: 'BAM', name: 'Босния и Герцеговина (конвертируемая марка Боснии и Герцеговины)', flagName: 'Bosnia-and-Herzegovina' },
  { code: 'BWP', name: 'Ботсвана (ботсванская пула)', flagName: 'Botswana' },
  { code: 'BRL', name: 'Бразилия (бразильский реал)', flagName: 'Brazil' },
  { code: 'BND', name: 'Бруней (брунейский доллар)', flagName: 'Brunei' },
  { code: 'BGN', name: 'Болгария (болгарский лев)', flagName: 'Bulgaria' },
  { code: 'BIF', name: 'Бурунди (бурундийский франк)', flagName: 'Burundi' },
  { code: 'KHR', name: 'Камбоджа (камбоджийский риель)', flagName: 'Cambodia' },
  { code: 'XAF', name: 'Камерун (франк КФА BEAC)', flagName: 'Cameroon' },
  { code: 'CAD', name: 'Канада (канадский доллар)', flagName: 'Canada' },
  { code: 'CVE', name: 'Кабо-Верде (эскудо Кабо-Верде)', flagName: 'Cape-Verde' },
  { code: 'KYD', name: 'Каймановы острова (доллар Островов Кайман)', flagName: 'Cayman-Islands' },
  { code: 'CLP', name: 'Чили (чилийский песо)', flagName: 'Chile' },
  { code: 'CNY', name: 'Китай (китайский юань)', flagName: 'China' },
  { code: 'COP', name: 'Колумбия (колумбийский песо)', flagName: 'Colombia' },
  { code: 'KMF', name: 'Коморы (коморский франк)', flagName: 'Comoros' },
  { code: 'NZD', name: 'Острова Кука (новозеландский доллар)', flagName: 'Cook-Islands' },
  { code: 'CRC', name: 'Коста-Рика (костариканский колон)', flagName: 'Costa-Rica' },
  { code: 'CUP', name: 'Куба (кубинский песо)', flagName: 'Cuba' },
  { code: 'XCG', name: 'Кюрасао (XCG)', flagName: 'Curacao' },
  { code: 'CZK', name: 'Чехия (чешская крона)', flagName: 'Czech-Republic' },
  { code: 'CDF', name: 'Демократическая Республика Конго (конголезский франк)', flagName: 'Democratic-Republic-of-the-Congo' },
  { code: 'DKK', name: 'Дания (датская крона)', flagName: 'Denmark' },
  { code: 'DJF', name: 'Джибути (франк Джибути)', flagName: 'Djibouti' },
  { code: 'DOP', name: 'Доминиканская Республика (доминиканский песо)', flagName: 'Dominican-Republic' },
  { code: 'EGP', name: 'Египет (египетский фунт)', flagName: 'Egypt' },
  { code: 'GBP', name: 'Англия (британский фунт стерлингов)', flagName: 'England' },
  { code: 'ERN', name: 'Эритрея (эритрейская накфа)', flagName: 'Eritrea' },
  { code: 'ETB', name: 'Эфиопия (эфиопский быр)', flagName: 'Ethiopia' },
  { code: 'FKP', name: 'Фолклендские острова (фунт Фолклендских островов)', flagName: 'Falkland-Islands' },
  { code: 'FJD', name: 'Фиджи (доллар Фиджи)', flagName: 'Fiji' },
  { code: 'XPF', name: 'Французская Полинезия (французский тихоокеанский франк)', flagName: 'French-Polynesia' },
  { code: 'GMD', name: 'Гамбия (гамбийский даласи)', flagName: 'Gambia' },
  { code: 'GEL', name: 'Грузия (грузинский лари)', flagName: 'Georgia' },
  { code: 'GHS', name: 'Гана (ганский седи)', flagName: 'Ghana' },
  { code: 'GIP', name: 'Гибралтар (гибралтарский фунт)', flagName: 'Gibraltar' },
  { code: 'GTQ', name: 'Гватемала (гватемальский кетсаль)', flagName: 'Guatemala' },
  { code: 'GNF', name: 'Гвинея (гвинейский франк)', flagName: 'Guinea' },
  { code: 'GYD', name: 'Гайана (гайанский доллар)', flagName: 'Guyana' },
  { code: 'HTG', name: 'Гаити (гаитянский гурд)', flagName: 'Haiti' },
  { code: 'HNL', name: 'Гондурас (гондурасская лемпира)', flagName: 'Honduras' },
  { code: 'HKD', name: 'Гонконг (гонконгский доллар)', flagName: 'Hong-Kong' },
  { code: 'HUF', name: 'Венгрия (венгерский форинт)', flagName: 'Hungary' },
  { code: 'ISK', name: 'Исландия (исландская крона)', flagName: 'Iceland' },
  { code: 'IDR', name: 'Индонезия (индонезийская рупия)', flagName: 'Indonesia' },
  { code: 'IRR', name: 'Иран (иранский риал)', flagName: 'Iran' },
  { code: 'IQD', name: 'Ирак (иракский динар)', flagName: 'Iraq' },
  { code: 'ILS', name: 'Израиль (новый израильский шекель)', flagName: 'Israel' },
  { code: 'JMD', name: 'Ямайка (ямайский доллар)', flagName: 'Jamaica' },
  { code: 'JPY', name: 'Япония (японская иена)', flagName: 'Japan' },
  { code: 'JOD', name: 'Иордания (иорданский динар)', flagName: 'Jordan' },
  { code: 'KZT', name: 'Казахстан (казахский тенге)', flagName: 'Kazakhstan' },
  { code: 'KES', name: 'Кения (кенийский шиллинг)', flagName: 'Kenya' },
  { code: 'KWD', name: 'Кувейт (кувейтский динар)', flagName: 'Kuwait' },
  { code: 'KGS', name: 'Киргизия (киргизский сом)', flagName: 'Kyrgyzstan' },
  { code: 'LAK', name: 'Лаос (лаосский кип)', flagName: 'Laos' },
  { code: 'LBP', name: 'Ливан (ливанский фунт)', flagName: 'Lebanon' },
  { code: 'ZAR', name: 'Лесото (южноафриканский рэнд)', flagName: 'Lesotho' },
  { code: 'LRD', name: 'Либерия (либерийский доллар)', flagName: 'Liberia' },
  { code: 'LYD', name: 'Ливия (ливийский динар)', flagName: 'Libya' },
  { code: 'CHF', name: 'Лихтенштейн (швейцарский франк)', flagName: 'Liechtenstein' },
  { code: 'MOP', name: 'Макао (патака Макао)', flagName: 'Macau' },
  { code: 'MKD', name: 'Северная Македония (македонский денар)', flagName: 'Macedonia' },
  { code: 'MGA', name: 'Мадагаскар (малагасийский ариари)', flagName: 'Madagascar' },
  { code: 'MWK', name: 'Малави (малавийская квача)', flagName: 'Malawi' },
  { code: 'MYR', name: 'Малайзия (малайзийский ринггит)', flagName: 'Malaysia' },
  { code: 'MVR', name: 'Мальдивы (мальдивская руфия)', flagName: 'Maldives' },
  { code: 'MRU', name: 'Мавритания (мавританская угия)', flagName: 'Mauritania' },
  { code: 'MUR', name: 'Маврикий (маврикийская рупия)', flagName: 'Mauritius' },
  { code: 'MXN', name: 'Мексика (мексиканский песо)', flagName: 'Mexico' },
  { code: 'MDL', name: 'Молдова (молдавский лей)', flagName: 'Moldova' },
  { code: 'MNT', name: 'Монголия (монгольский тугрик)', flagName: 'Mongolia' },
  { code: 'MAD', name: 'Марокко (марокканский дирхам)', flagName: 'Morocco' },
  { code: 'MZN', name: 'Мозамбик (мозамбикский метикал)', flagName: 'Mozambique' },
  { code: 'MMK', name: 'Мьянма (мьянманский кьят)', flagName: 'Myanmar' },
  { code: 'NPR', name: 'Непал (непальская рупия)', flagName: 'Nepal' },
  { code: 'ANG', name: 'Нидерландские Антильские острова (нидерландский антильский гульден)', flagName: 'Netherlands-Antilles' },
  { code: 'NIO', name: 'Никарагуа (никарагуанская кордоба)', flagName: 'Nicaragua' },
  { code: 'NGN', name: 'Нигерия (нигерийская найра)', flagName: 'Niger' },
  { code: 'KPW', name: 'Северная Корея (северокорейская вона)', flagName: 'North-Korea' },
  { code: 'NOK', name: 'Норвегия (норвежская крона)', flagName: 'Norway' },
  { code: 'OMR', name: 'Оман (оманский риал)', flagName: 'Oman' },
  { code: 'PKR', name: 'Пакистан (пакистанская рупия)', flagName: 'Pakistan' },
  { code: 'PAB', name: 'Панама (панамский бальбоа)', flagName: 'Panama' },
  { code: 'PGK', name: 'Папуа — Новая Гвинея (кина Папуа – Новой Гвинеи)', flagName: 'Papua-New-Guinea' },
  { code: 'PYG', name: 'Парагвай (парагвайский гуарани)', flagName: 'Paraguay' },
  { code: 'PEN', name: 'Перу (перуанский соль)', flagName: 'Peru' },
  { code: 'PHP', name: 'Филиппины (филиппинский песо)', flagName: 'Philippines' },
  { code: 'PLN', name: 'Польша (польский злотый)', flagName: 'Poland' },
  { code: 'QAR', name: 'Катар (катарский риал)', flagName: 'Qatar' },
  { code: 'RON', name: 'Румыния (румынский лей)', flagName: 'Romania' },
  { code: 'RUB', name: 'Россия (российский рубль)', flagName: 'Russia' },
  { code: 'RWF', name: 'Руанда (франк Руанды)', flagName: 'Rwanda' },
  { code: 'SHP', name: 'о-в Св. Елены (фунт острова Святой Елены)', flagName: 'Saint-Helena' },
  { code: 'WST', name: 'Самоа (самоанская тала)', flagName: 'Samoa' },
  { code: 'STN', name: 'Сан-Томе и Принсипи (добра Сан-Томе и Принсипи)', flagName: 'Sao-Tome-and-Principe' },
  { code: 'SAR', name: 'Саудовская Аравия (саудовский риял)', flagName: 'Saudi-Arabia' },
  { code: 'RSD', name: 'Сербия (сербский динар)', flagName: 'Serbia' },
  { code: 'SCR', name: 'Сейшельские острова (сейшельская рупия)', flagName: 'Seychelles' },
  { code: 'SLE', name: 'Сьерра-Леоне (леоне)', flagName: 'Sierra-Leone' },
  { code: 'SGD', name: 'Сингапур (сингапурский доллар)', flagName: 'Singapore' },
  { code: 'SBD', name: 'Соломоновы острова (доллар Соломоновых Островов)', flagName: 'Solomon-Islands' },
  { code: 'SOS', name: 'Сомали (сомалийский шиллинг)', flagName: 'Somalia' },
  { code: 'KRW', name: 'Южная Корея (южнокорейская вона)', flagName: 'South-Korea' },
  { code: 'SSP', name: 'Южный Судан (южносуданский фунт)', flagName: 'South-Sudan' },
  { code: 'LKR', name: 'Шри-Ланка (шри-ланкийская рупия)', flagName: 'Sri-Lanka' },
  { code: 'SDG', name: 'Судан (суданский фунт)', flagName: 'Sudan' },
  { code: 'SRD', name: 'Суринам (суринамский доллар)', flagName: 'Suriname' },
  { code: 'SZL', name: 'Эсватини (свазилендский лилангени)', flagName: 'Swaziland' },
  { code: 'SEK', name: 'Швеция (шведская крона)', flagName: 'Sweden' },
  { code: 'SYP', name: 'Сирия (сирийский фунт)', flagName: 'Syria' },
  { code: 'TWD', name: 'Тайвань (новый тайваньский доллар)', flagName: 'Taiwan' },
  { code: 'TJS', name: 'Таджикистан (таджикский сомони)', flagName: 'Tajikistan' },
  { code: 'TZS', name: 'Танзания (танзанийский шиллинг)', flagName: 'Tanzania' },
  { code: 'THB', name: 'Таиланд (таиландский бат)', flagName: 'Thailand' },
  { code: 'TOP', name: 'Тонга (тонганская паанга)', flagName: 'Tonga' },
  { code: 'TTD', name: 'Тринидад и Тобаго (доллар Тринидада и Тобаго)', flagName: 'Trinidad-and-Tobago' },
  { code: 'TND', name: 'Тунис (тунисский динар)', flagName: 'Tunisia' },
  { code: 'TRY', name: 'Северный Кипр (турецкая лира)', flagName: 'Northern-Cyprus' },
  { code: 'TMT', name: 'Туркменистан (новый туркменский манат)', flagName: 'Turkmenistan' },
  { code: 'UGX', name: 'Уганда (угандийский шиллинг)', flagName: 'Uganda' },
  { code: 'UAH', name: 'Украина (украинская гривна)', flagName: 'Ukraine' },
  { code: 'AED', name: 'ОАЭ (дирхам ОАЭ)', flagName: 'United-Arab-Emirates' },
  { code: 'UYU', name: 'Уругвай (уругвайский песо)', flagName: 'Uruguay' },
  { code: 'UZS', name: 'Узбекистан (узбекский сум)', flagName: 'Uzbekistan' },
  { code: 'VUV', name: 'Вануату (вату Вануату)', flagName: 'Vanuatu' },
  { code: 'VES', name: 'Венесуэла (венесуэльский боливар)', flagName: 'Venezuela' },
  { code: 'VND', name: 'Вьетнам (вьетнамский донг)', flagName: 'Vietnam' },
  { code: 'YER', name: 'Йемен (йеменский риал)', flagName: 'Yemen' },
  { code: 'ZMW', name: 'Замбия (замбийская квача)', flagName: 'Zambia' },
];
